
import React from 'react';
import {
  Megaphone, Search, Music, Film,
  FileText, MessageCircle, Gift, HelpCircle,
  Mail, MessagesSquare, BookOpen, Star,
  PlaySquare, ShoppingCart, CreditCard, PlusCircle, TrendingUp,
  MailCheck, UserCheck, Users, MessageSquarePlus,
  RefreshCw, MailWarning, TrendingDown,
  CalendarPlus, FileSignature, ImageIcon, VideoIcon, AudioLines, StickyNote, Blocks
} from 'lucide-react';

export type BlockCategory = 
  'Extras / Complementares' |
  'Atração' | 'Captura' | 'Nutrição' | 'Oferta' | 'Pós-venda' | 'Remarketing' | 'Especiais';

export interface BlockType {
  type: string;
  label: string;
  category: BlockCategory;
  description: string;
  linkExample?: string;
  extra?: string;
  icon: React.ReactElement;
  color: string;
  hasDescription?: boolean;
  hasLink?: boolean;
}

export const blockTypes: BlockType[] = [
  // 5. EXTRAS / COMPLEMENTARES
  {
    type: 'notes',
    label: 'Anotação',
    category: 'Extras / Complementares',
    description: 'Adicione anotações, lembretes e observações diretamente no seu funil.',
    extra: 'Use para explicar partes complexas do fluxo ou para deixar ideias para depois.',
    icon: React.createElement(StickyNote),
    color: '#FBBF24',
  },
  
  // FUNNEL BLOCKS (Existing)
  {
    type: 'meta-ads',
    label: 'Meta Ads',
    category: 'Atração',
    description: 'Tráfego frio vindo de Facebook ou Instagram.',
    linkExample: '(gerado no Gerenciador de Anúncios)',
    extra: 'Usar imagem ou vídeo curto + headline emocional.',
    icon: React.createElement(Megaphone),
    color: '#3B82F6',
    hasLink: true,
  },
  {
    type: 'google-ads',
    label: 'Google Ads',
    category: 'Atração',
    description: 'Tráfego de busca ou remarketing.',
    linkExample: 'google.com/ads',
    extra: 'Palavras-chave de intenção > conversão.',
    icon: React.createElement(Search),
    color: '#EA4335',
    hasLink: true,
  },
  {
    type: 'tiktok-ads',
    label: 'TikTok Ads',
    category: 'Atração',
    description: 'Criativos rápidos e virais para jovens públicos.',
    linkExample: 'ads.tiktok.com',
    extra: 'Boas para dor/emocional/humor.',
    icon: React.createElement(Music),
    color: '#010101',
    hasLink: true,
  },
  {
    type: 'reels-shorts',
    label: 'Reels / Shorts',
    category: 'Atração',
    description: 'Vídeos curtos de impacto para atrair leads.',
    linkExample: 'Instagram ou YouTube Shorts',
    extra: 'Usar CTA para directs ou link na bio.',
    icon: React.createElement(Film),
    color: '#C13584',
    hasLink: true,
  },
  {
    type: 'landing-page',
    label: 'Página de Captura',
    category: 'Captura',
    description: 'Formulário para pegar e-mail, WhatsApp, etc.',
    linkExample: '(criada via builder como Klickpages, LeadLovers, etc.)',
    extra: 'Usar isca digital e prova social.',
    icon: React.createElement(FileText),
    color: '#10B981',
    hasLink: true,
  },
  {
    type: 'whatsapp-link',
    label: 'Link para WhatsApp',
    category: 'Captura',
    description: 'Envia lead direto para conversa.',
    linkExample: 'https://wa.me/SEUNUMERO?text=Olá%2C+quero+saber+mais!',
    extra: 'Usar texto de pré-qualificação.',
    icon: React.createElement(MessageCircle),
    color: '#25D366',
    hasLink: true,
  },
  {
    type: 'digital-bait',
    label: 'Isca Digital',
    category: 'Captura',
    description: 'PDF, checklist, planilha, mini-aula etc.',
    linkExample: 'Hospedado no Drive ou servidor próprio',
    extra: 'Promessa clara e entrega instantânea.',
    icon: React.createElement(Gift),
    color: '#F59E0B',
    hasLink: true,
  },
  {
    type: 'interactive-quiz',
    label: 'Quiz Interativo',
    category: 'Captura',
    description: 'Captação e segmentação em uma só página.',
    linkExample: 'Typeform, Tryinteract, etc.',
    extra: 'Aumenta engajamento e coleta dados ricos.',
    icon: React.createElement(HelpCircle),
    color: '#8B5CF6',
    hasLink: true,
  },
  {
    type: 'email-sequence',
    label: 'Sequência de E-mails',
    category: 'Nutrição',
    description: 'Envio programado de conteúdos com storytelling.',
    linkExample: 'via ActiveCampaign, Mailchimp, etc.',
    extra: 'Quebrar objeções aos poucos.',
    icon: React.createElement(Mail),
    color: '#6366F1',
  },
  {
    type: 'whatsapp-funnel',
    label: 'Funil WhatsApp',
    category: 'Nutrição',
    description: 'Conteúdos em texto/áudio/vídeo via broadcast ou grupo.',
    linkExample: 'Manychat, GHL, Z-API, etc.',
    extra: 'CTA claro e cronograma leve (ex: 1x/dia).',
    icon: React.createElement(MessagesSquare),
    color: '#128C7E',
  },
  {
    type: 'mini-course',
    label: 'Minicurso / Série',
    category: 'Nutrição',
    description: 'Sequência de vídeos antes da oferta.',
    linkExample: 'YouTube, Vimeo ou área de membros',
    extra: 'Bom para funis de lançamento ou perpétuos.',
    icon: React.createElement(BookOpen),
    color: '#EF4444',
    hasLink: true,
  },
  {
    type: 'vip-list',
    label: 'Lista VIP',
    category: 'Nutrição',
    description: 'Canal de valor e proximidade no Telegram ou WhatsApp.',
    linkExample: 'Convite para grupo privado',
    extra: 'Gerar escassez e exclusividade.',
    icon: React.createElement(Star),
    color: '#FBBF24',
    hasLink: true,
  },
  {
    type: 'vsl',
    label: 'VSL',
    category: 'Oferta',
    description: 'Vídeo de 5 a 20min com pitch estruturado.',
    linkExample: 'Embed no site ou hospedado no YouTube/Vimeo',
    extra: 'Usar fórmula AIDA ou PASTOR.',
    icon: React.createElement(PlaySquare),
    color: '#DC2626',
    hasLink: true,
  },
  {
    type: 'sales-page',
    label: 'Página de Vendas',
    category: 'Oferta',
    description: 'Copy com estrutura completa (headline, dor, prova, oferta).',
    linkExample: 'ex: funil.me/oferta',
    extra: 'Pode ter vídeo ou ser só texto.',
    icon: React.createElement(ShoppingCart),
    color: '#22C55E',
    hasLink: true,
  },
  {
    type: 'direct-checkout',
    label: 'Checkout Direto',
    category: 'Oferta',
    description: 'Vai direto para pagamento (sem página).',
    linkExample: 'Gerado por Hotmart, Kiwify, Yampi, etc.',
    extra: 'Bom para tráfego quente e rápido.',
    icon: React.createElement(CreditCard),
    color: '#16A34A',
    hasLink: true,
  },
  {
    type: 'order-bump',
    label: 'Order Bump',
    category: 'Oferta',
    description: 'Item extra vendido no momento do checkout.',
    linkExample: 'Configurado dentro da plataforma de checkout',
    extra: 'Valor mais baixo e complementar (ex: R$27).',
    icon: React.createElement(PlusCircle),
    color: '#F97316',
    hasLink: true,
  },
  {
    type: 'upsell',
    label: 'Upsell',
    category: 'Oferta',
    description: 'Nova oferta após a compra com 1 clique.',
    linkExample: 'Ativado automaticamente no checkout',
    extra: 'Aumentar ticket com produto complementar.',
    icon: React.createElement(TrendingUp),
    color: '#F59E0B',
    hasLink: true,
  },
  {
    type: 'welcome-email',
    label: 'E-mail de Boas-Vindas',
    category: 'Pós-venda',
    description: 'Agradecimento + instrução de acesso.',
    linkExample: 'Enviado automaticamente via e-mail',
    extra: 'Reforçar decisão do cliente.',
    icon: React.createElement(MailCheck),
    color: '#10B981',
  },
  {
    type: 'onboarding',
    label: 'Onboarding',
    category: 'Pós-venda',
    description: 'Vídeos curtos para guiar o novo cliente.',
    linkExample: 'Área de membros ou e-mail',
    extra: 'Reduzir churn, aumentar uso.',
    icon: React.createElement(UserCheck),
    color: '#3B82F6',
    hasLink: true,
  },
  {
    type: 'community',
    label: 'Comunidade',
    category: 'Pós-venda',
    description: 'Ambiente para engajar clientes (Facebook, WhatsApp, Discord).',
    linkExample: 'Convite enviado após compra',
    extra: 'Reforça autoridade e proximidade.',
    icon: React.createElement(Users),
    color: '#8B5CF6',
    hasLink: true,
  },
  {
    type: 'testimonial-request',
    label: 'Pedido de Depoimento',
    category: 'Pós-venda',
    description: 'Coleta de prova social.',
    linkExample: 'Pode usar Google Forms ou Typeform',
    extra: 'Oferecer bônus em troca.',
    icon: React.createElement(MessageSquarePlus),
    color: '#6366F1',
  },
  {
    type: 'remarketing-ad',
    label: 'Anúncio Remarketing',
    category: 'Remarketing',
    description: 'Anúncio para quem não comprou ou abandonou.',
    linkExample: 'Criado via Meta Ads ou Google',
    extra: 'Usar gatilhos diferentes (escassez, depoimento, bônus).',
    icon: React.createElement(RefreshCw),
    color: '#78716C',
    hasLink: true,
  },
  {
    type: 'recovery-email',
    label: 'E-mail Recuperação',
    category: 'Remarketing',
    description: 'Lembrar o lead da compra incompleta.',
    linkExample: 'E-mail com botão de retorno para checkout',
    extra: 'Reforçar urgência ou benefício.',
    icon: React.createElement(MailWarning),
    color: '#F59E0B',
  },
  {
    type: 'whatsapp-rescue',
    label: 'WhatsApp Resgate',
    category: 'Remarketing',
    description: 'Abordagem direta com nova oferta.',
    linkExample: 'Enviado com mensagem personalizada',
    extra: 'Usar nome da pessoa + novo argumento.',
    icon: React.createElement(MessageCircle),
    color: '#16A34A',
  },
  {
    type: 'downsell',
    label: 'Downsell',
    category: 'Especiais',
    description: 'Oferta mais barata após não compra.',
    linkExample: 'Redirecionado automaticamente',
    extra: 'Pode ser parcelamento ou versão light.',
    icon: React.createElement(TrendingDown),
    color: '#EF4444',
    hasLink: true,
  },
  {
    type: 'schedule-call',
    label: 'Agendamento de Call',
    category: 'Especiais',
    description: 'Lead marca reunião com vendedor.',
    linkExample: 'Calendly, Tidycal',
    extra: 'Aplicar quando ticket > R$1.000.',
    icon: React.createElement(CalendarPlus),
    color: '#0EA5E9',
    hasLink: true,
  },
  {
    type: 'commercial-proposal',
    label: 'Proposta Comercial',
    category: 'Especiais',
    description: 'Envio de proposta personalizada.',
    linkExample: 'Google Docs, Notion, PDF link',
    extra: 'Aplicar para serviços ou B2B.',
    icon: React.createElement(FileSignature),
    color: '#475569',
    hasLink: true,
  },
  {
    type: 'image-upload',
    label: 'Adicionar Imagem',
    category: 'Especiais',
    description: 'Carregue uma imagem do seu dispositivo para usar no funil.',
    extra: 'Ideal para banners, provas sociais visuais ou mockups.',
    icon: React.createElement(ImageIcon),
    color: '#34D399',
  },
  {
    type: 'video-upload',
    label: 'Adicionar Vídeo',
    category: 'Especiais',
    description: 'Carregue um vídeo do seu dispositivo.',
    extra: 'Use para depoimentos, demonstrações ou tutoriais curtos.',
    icon: React.createElement(VideoIcon),
    color: '#F87171',
  },
  {
    type: 'audio-upload',
    label: 'Adicionar Áudio',
    category: 'Especiais',
    description: 'Carregue um áudio do seu dispositivo.',
    extra: 'Perfeito para depoimentos em áudio, podcasts ou narrações.',
    icon: React.createElement(AudioLines),
    color: '#60A5FA',
  },
  {
    type: 'pdf-upload',
    label: 'Adicionar PDF',
    category: 'Especiais',
    description: 'Carregue um arquivo PDF do seu dispositivo para usar no funil.',
    extra: 'Ideal para iscas digitais, contratos ou materiais de apoio.',
    icon: React.createElement(FileText),
    color: '#64748B',
  },
  {
    type: 'all-in-one',
    label: 'Bloco "Tudo em Um"',
    category: 'Especiais',
    description: 'Um bloco versátil que pode conter um link, arquivo, valor, e mais.',
    extra: 'Use para criar etapas complexas do funil com um único elemento.',
    icon: React.createElement(Blocks),
    color: '#9333ea',
    hasLink: true,
  },
];

export const findBlockByType = (type: string): BlockType | undefined => {
    return blockTypes.find(b => b.type === type);
}
